Neos:
  SwiftMailer:
    transport:
      type: 'Swift_MailTransport'
      arguments: ~
      options: []

# Example settings for sending emails via SMTP / SSL:
#
# SwiftMailer:
#   transport:
#     type: 'Swift_SmtpTransport'
#     options:
#       host: 'smtp.example.com'
#       port: 465
#       username: 'myaccount@example.com'
#       password: '5js9j1lkjs8'
#       localDomain: 'example.com'

# Example settings for "sending" emails to an mbox file:
#
# SwiftMailer:
#   transport:
#     type: 'Neos\SwiftMailer\Transport\MboxTransport'
#     options:
#       mboxPathAndFilename: '%FLOW_PATH_DATA%/Persistent/sent-mail'

